### PR TITLE
Suggesting switching to htop-vim by default

### PR DESCRIPTION
**Pull request by ViktorWalter**
What it says on the tin. Htop does not support proper keybindings by default.

### CODE REVIEW

**Comment by ViktorWalter** [comment]
Ok, thanks.
1) It is probably missing some dependencies for you - I'll have to try building it on a clean machine to find out which, the README does not list them.
2,3) Ok, sure

**Comment by klaxalk** [comment]
> Ok, thanks.
> 
> 1. * It is probably missing some dependencies for you - I'll have to try building it on a clean machine to find out which, the README does not list them.
> 
> 2.,3. - Ok, sure

Eh, you don't have to build it on a clean machine, the "Travis CI" just did that for you. Check it's output.

**Comment by ViktorWalter** [comment]
Ah, yes, I see now. `./install.sh: "cd ~/git" command failed with exit code 1`. Ok

**Comment by klaxalk** [comment]
It's there.

**Pull request closed without merging**
