### PR TITLE
update YCM to the latest version

### PR DESCRIPTION
**Pull request by matemat13**
The latest YouCompleteMe version uses `clangd` instead of `clang`, which should work better and enables some more features (e.g. smart renaming and other refactoring features). Includes other minor fixes as well.

### CODE REVIEW

**Comment by klaxalk** [comment]
Hmm, we should split the installation and runtime for 18.04 and 20.04 if possible. The DARPA guys will still likely use 18.04 this year.

**Comment by matemat13** [comment]
uhh... that sucks :( That'd mean compiling clangd-11 manually (it's not available in 18.04). I'll look into this - maybe we can use downloadable binaries in case of 18.04.

**Comment by klaxalk** [comment]
Would it be possible to condition the installation on 18.04 such that it is the old version? Epigen could help with the configs.. and we can make it require a user action… since it not priority. But we should leave them the option.

**Comment by klaxalk** [comment]
Thanks a lot @matemat13, really appreciate it :-). Have a few beers on me.

**Pull request merged**
